dist: xenial
language: ruby
rvm: 2.6.3
script: bundle exec rake spec
env:
  - ENGINE=ruby
  - ENGINE=narray
  - ENGINE=numo-narray
notifications:
  email:
    on_success: never
    on_failure: change
